### ISSUE TITLE
User login

### ISSUE THREAD

**Issue by alanvardy** [alanvardy/health#1]
I would like to have a username/password combo option, but also OAuth2. So lets keep the login separate from the accounts?

The Programming Phoenix book has a good example of this.

**Comment by alanvardy** [comment]
Do we want to try a major library for this stuff? Guardian?

**Comment by matt-riemer** [comment]
Guardian +1

**Comment by alanvardy** [comment]
Guardian it is!

**Comment by alanvardy** [comment]
Having second thoughts here Matt!

http://cryto.net/~joepie91/blog/2016/06/13/stop-using-jwt-for-sessions/

I'm doing some research and a lot of people recommend JWTs for APIs and NOT for regular HTTP requests. Guardian doesn't do any session based stuff. Thoughts?

I have just been storing user_id in a secure session cookie up until this point with mucho success. I'm not against trying a good library though :)

**Comment by alanvardy** [comment]
How about Pow?
https://hexdocs.pm/pow/README.html#content
https://github.com/danschultzer/pow

**Comment by alanvardy** [comment]
I'm looking around at some other ones too but so far Pow looks like it has some really good docs.

**Comment by matt-riemer** [comment]
+1 for pow.  I'm interested in a gem that basically provides devise level replacement.

This looks pretty good

**Comment by alanvardy** [comment]
Done with pow!
