### ISSUE TITLE
Plotly.js doesn't work on Firefox

### ISSUE THREAD

**Issue by matt-riemer** [alanvardy/health#94]
Straight up busted on Firefox.

I tried plucking some old versions instead of the CDN plotly.latest but no dice

![Health_-_A_Phoenix_app_for_keeping_us_above_ground_a_little_longer](https://user-images.githubusercontent.com/954468/61220559-c8e0d980-a6d3-11e9-910b-3fe8c00c073a.png)

**Comment by alanvardy** [comment]
Nuts! Has it ever worked for you before?

**Comment by matt-riemer** [comment]
Nope :(

**Comment by alanvardy** [comment]
Seems to be an ongoing issue with firefox
https://github.com/JuliaPlots/Plots.jl/issues/1138
